stages:
  prepare:
    cmd: python3 src/preprocessing.py data/heart.csv data/X_processed.csv data/y.csv data/preprocessor.pkl
    deps:
      - data/heart.csv
      - src/preprocessing.py
    outs:
      - data/X_processed.csv
      - data/y.csv
      - data/preprocessor.pkl