apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mlflow_test
        imagePullPolicy: Never     # 👈 THIS LINE IS IMPORTANT
        ports:
        - containerPort: 5000